openapi: "3.0.1"
info:
  title: Users Service API
  description: Users Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:

  /read_message/{id_mess}:
    get:
      tags: [Messages]
      parameters:
        - in: path
          name: id_mess
          required: true
          schema:
            type: integer
            format: int64
          description: id of the mess
      description: Gets the message to read
      operationId: mib.resources.messages.read_message
      responses:
        200:
          description: Return the selected message
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        404:
          description: Message not found
        default:
          description: An error occured during retrieving the message