openapi: "3.0.1"
info:
  title: Users Service API
  description: Users Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:
  /message/list/sent/{id_usr}:
    get:
      tags: [ Messages ]
      parameters:
        - in: path
          name: id_usr
          required: true
          schema:
            type: integer
            format: int64
          description: id of the user
      description: Gets the list of sent messages by the user
      operationId: mib.resources.messages.message_list_sent
      responses:
        200:
          description: Return the list of sent messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
                  images:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: name of the image file
                        data:
                          type: string
                          description: data of the image
                        type:
                          type: string
                          description: type of the image
        default:
          description: An error occured while retrieving the message

  /message/{id_mess}/read/{id_usr}:
    get:
      tags: [Messages]
      parameters:
        - in: path
          name: id_mess
          required: true
          schema:
            type: integer
            format: int64
          description: id of the mess
        - in: path
          name: id_usr
          required: true
          schema:
            type: integer
            format: int64
          description: id of the user
      description: Gets the message to read
      operationId: mib.resources.messages.read_message
      responses:
        200:
          description: Return the selected message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    $ref: '#/components/schemas/Message'
                  image:
                    type: object
                    properties:
                      name:
                        type: string
                        description: name of the image file
                      data:
                        type: string
                        description: data of the image
                      type:
                        type: string
                        description: type of the image
        404:
          description: Message not found
        401:
          description: User not allow to read the message
        default:
          description: An error occured during retrieving the message

components:
  schemas:
    Message:
      type: object
      properties:
        id_message:
          type: integer
          description: Message id
          format: int64
        id_sender:
          type: integer
          description: Sender id
          format: int64
        recipients:
          type: array
          items:
            type: integer # TODO edit
          description: List of recipients for the message
        message_body:
          type: string
          description: Message body
        delivery_date:
          type: string
          description: Delivery date of the message
        is_sent:
          type: boolean
          description: flag set to true if the message has been sent
        is_arrived:
          type: boolean
          description: flag set to true if the message has been delivered
        to_filter:
          type: boolean
          description: flag set to true if the message has unsafe words in its body
        reply_to:
          type: integer
          format: int64
          description: id of the message this one is a reply for



