"""empty message

Revision ID: 8571d656828a
Revises: 
Create Date: 2021-12-08 15:37:56.927099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8571d656828a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Message",
        sa.Column("id_message", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_sender", sa.Integer(), nullable=True),
        sa.Column("message_body", sa.Unicode(length=256), nullable=True),
        sa.Column("img_path", sa.Unicode(length=128), nullable=True),
        sa.Column("delivery_date", sa.DateTime(), nullable=True),
        sa.Column("is_sent", sa.Boolean(), nullable=True),
        sa.Column("is_arrived", sa.Boolean(), nullable=True),
        sa.Column("to_filter", sa.Boolean(), nullable=True),
        sa.Column("reply_to", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_message"),
    )
    op.create_table(
        "Recipient",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_message", sa.Integer(), nullable=True),
        sa.Column("id_recipient", sa.Integer(), nullable=True),
        sa.Column("has_opened", sa.Boolean(), nullable=True),
        sa.Column("read_deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_message"],
            ["Message.id_message"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Recipient")
    op.drop_table("Message")
    # ### end Alembic commands ###
